preload = /home/shivang/walls/wp6689718-desktop-4k-forest-way-wallpapers.jpg

wallpaper {
    monitor = eDP-1
    path = /home/shivang/walls/wp6689718-desktop-4k-forest-way-wallpapers.jpg
    fit_mode = cover
}   
