# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# windowrule = opacity 0.75 0.75, title:(.*)$
windowrule = float,class:xdg-desktop-portal-gtk
windowrule = float, title:popup
windowrule = size 700 350,title:popup
