# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# windowrule = opacity 0.75 0.75, title:(.*)$
windowrule = match:class xdg-desktop-portal-gtk,float on
windowrule = match:title popup,float on
windowrule = match:title popup,size 700 350
